import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/Navbar";
import { getAllProducts } from "@/lib/products";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = localFont({
  src: [
    {
      path: "../../fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Baydoun Watches",
  description: "Generated by Moe Jardani",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products = await getAllProducts();

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar products={products} />
        {children}
        <Toaster
          toastOptions={{
            position: "bottom-right",
            style: {
              background: "#0a0a0a",
              color: "#c9a84c",
              border: "1px solid #c9a84c",
              borderRadius: "8px",
              padding: "12px 16px",
              fontSize: "14px",
              fontWeight: "500",
            },
            duration: 5000,
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
