import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import ScrollReset from "../components/ScrollReset";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = localFont({
  src: [
    {
      path: "../fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Baydoun Watches",
  description: "Generated by Moe Jardani",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><ScrollReset />{children}</body>
    </html>
  );
}
